-- Import BRAND to ims_brand
-- Date: 2026-03-18 02:35:04

-- DB1 (sac_data)
INSERT INTO ims_brand (brand_id, brand_name, status) VALUES
('AD', 'ADVANCE PERFORMA', 'Active'),
('AL', 'ACHILLES', 'Active'),
('AP', 'apollo ยางเล็ก', 'Active'),
('AP.', 'AP ยางใหญ่', 'Active'),
('AT', 'ATLAS', 'Active'),
('AT.', 'ATLAS ยางใหญ่', 'Active'),
('ATW', 'ATW', 'Active'),
('AV', 'AV ยางใหญ่', 'Active'),
('BF', 'BFGoodrich', 'Active'),
('BKT', 'BKT', 'Active'),
('BS', 'BSยางเล็ก', 'Active'),
('BS.', 'ยางใหญ่', 'Active'),
('BZ', 'BONANZA', 'Active'),
('CASTROL GTX', 'คาสตรอล จีทีเอ็กซ์', 'Active'),
('CG', 'goodtire', 'Active'),
('CL', 'รวมยางส่งเคลม', 'Active'),
('CM', 'CAMEL', 'Active'),
('CT', 'CONTINENTAL', 'Active'),
('DBC', 'DOUBLECOIN', 'Active'),
('DL', 'DUNLOP', 'Active'),
('DR', 'DURO', 'Active'),
('DS', 'DSยางเล็ก', 'Active'),
('DS.', 'DS ยางใหญ่ Off Road', 'Active'),
('DS..', 'DS ยางใหญ่ TBR', 'Active'),
('DS...', 'DS ยางใหญ่ On Road', 'Active'),
('DT', 'DAYTON ยางเล็ก', 'Active'),
('DT.', 'DAYTON ยางใหญ่', 'Active'),
('ERP', 'ERP', 'Active'),
('FK', 'FALKEN', 'Active'),
('FR', 'FULLRUN', 'Active'),
('FS', 'FSยางเล็ก', 'Active'),
('FS.', 'FSยางใหญ่', 'Active'),
('FT', 'FORTUNE', 'Active'),
('FW', 'FULLWAY', 'Active'),
('GK', 'GRITKING', 'Active'),
('GL', 'GOLDEN LAND', 'Active'),
('GR', 'GOODRIDE', 'Active'),
('GT', 'GOODTRIP', 'Active'),
('GULF', 'GULF', 'Active'),
('GY', 'GOODYEAR', 'Active'),
('H', 'HITACHI', 'Active'),
('HK', 'HKยางเล็ก', 'Active'),
('HK.', 'HK ยางใหญ่', 'Active'),
('HR', 'HIHERO', 'Active'),
('HT', 'HUT TYRES', 'Active'),
('IRC', 'IRC', 'Active'),
('KD', 'KENDA', 'Active'),
('KM', 'KUMHO', 'Active'),
('LE', 'LEAO', 'Active'),
('LL', 'LINGLONG ยางใหญ่', 'Active'),
('LLIT', 'LINGLONG ยางเล็ก', 'Active'),
('LS', 'LANDSAIL', 'Active'),
('MAX001', 'SEVEN FIFTH', 'Active'),
('MAX002', 'YACHIYODA', 'Active'),
('MAX003', 'LENSO', 'Active'),
('MAX004', 'THE ONE MAX', 'Active'),
('MAX005', 'LTC', 'Active'),
('MAX006', 'มาสเจสติค', 'Active'),
('MAX007', 'บวรพัฒน์', 'Active'),
('MAX008', 'วีลแกลเลอรี่', 'Active'),
('MAX009', 'KC WHEEL', 'Active'),
('MAX010', 'TK SMART', 'Active'),
('MAX011', 'สแตมฟอร์ด', 'Active'),
('MAX012', 'แอล จี ออโต้วีล', 'Active'),
('MAX013', 'อีโมชั่นฯ', 'Active'),
('MAX014', 'ออโต้เพอร์ฟอเม้นท์', 'Active'),
('MAX015', 'HOF', 'Active'),
('MK', 'MICKEY THOMPSON', 'Active'),
('ML', 'MLยางเล็ก', 'Active'),
('ML.', 'ML ยางใหญ่', 'Active'),
('MS', 'MARSHAL', 'Active'),
('MT', 'MASTER', 'Active'),
('MX', 'MAXXIS', 'Active'),
('MX.', 'MX', 'Active'),
('MXR', 'MAXIRICE', 'Active'),
('NK', 'NIKA', 'Active'),
('NT', 'NITTO', 'Active'),
('OT', 'OTANI', 'Active'),
('P', 'รวมสินค้ามือ 2', 'Active'),
('P01', 'อะไหล่นอก', 'Active'),
('PK-2013', 'ยางปีเก่ารวมยี่ห้อ <= 2013', 'Active'),
('PL', 'PIRELLI', 'Active'),
('PR', 'PRINX', 'Active'),
('SL', 'SAILUN', 'Active'),
('SP', 'SUPERSTONE', 'Active'),
('ST', 'สยามไทร์', 'Active'),
('SUMAX', 'SUMAX', 'Active'),
('TATA', 'TATA', 'Active'),
('TATA-P08', 'TATA-PEN', 'Active'),
('TATA-P09', 'TATA-เบาะ', 'Active'),
('TL', 'TIANLI', 'Active'),
('TY', 'TOYO ยางเล็ก', 'Active'),
('UR', 'URยางเล็ก', 'Active'),
('VALVOLINE', 'วาโวลีน จีอีโอ', 'Active'),
('VB', 'VEE RUBBER', 'Active'),
('WIL', 'กะทะล้อ', 'Active'),
('WTL', 'WESTLAKE', 'Active'),
('YK', 'YOKOHAMA', 'Active')
ON DUPLICATE KEY UPDATE brand_name = VALUES(brand_name), status = VALUES(status);

-- DB2 (sac_data2)
INSERT INTO ims_brand (brand_id, brand_name, status) VALUES
('AD', 'ADVANCE PERFORMA', 'Active'),
('AL', 'ACHILLES', 'Active'),
('AP', 'apollo ยางเล็ก', 'Active'),
('AP.', 'AP ยางใหญ่', 'Active'),
('AT', 'ATLAS', 'Active'),
('AT.', 'ATLAS ยางใหญ่', 'Active'),
('ATW', 'ATW', 'Active'),
('AV', 'AV ยางใหญ่', 'Active'),
('BF', 'BFGoodrich', 'Active'),
('BKT', 'BKT', 'Active'),
('BS', 'BSยางเล็ก', 'Active'),
('BS.', 'ยางใหญ่', 'Active'),
('BZ', 'BONANZA', 'Active'),
('CASTROL GTX', 'คาสตรอล จีทีเอ็กซ์', 'Active'),
('CG', 'goodtire', 'Active'),
('CL', 'รวมยางส่งเคลม', 'Active'),
('CM', 'CAMEL', 'Active'),
('CT', 'CONTINENTAL', 'Active'),
('DBC', 'DOUBLECOIN', 'Active'),
('DL', 'DUNLOP', 'Active'),
('DR', 'DURO', 'Active'),
('DS', 'DSยางเล็ก', 'Active'),
('DS.', 'DS ยางใหญ่ Off Road', 'Active'),
('DS..', 'DS ยางใหญ่ TBR', 'Active'),
('DS...', 'DS ยางใหญ่ On Road', 'Active'),
('DT', 'DAYTON ยางเล็ก', 'Active'),
('DT.', 'DAYTON ยางใหญ่', 'Active'),
('ERP', 'ERP', 'Active'),
('FK', 'FALKEN', 'Active'),
('FR', 'FULLRUN', 'Active'),
('FS', 'FSยางเล็ก', 'Active'),
('FS.', 'FSยางใหญ่', 'Active'),
('FT', 'FORTUNE', 'Active'),
('FW', 'FULLWAY', 'Active'),
('GK', 'GRITKING', 'Active'),
('GL', 'GOLDEN LAND', 'Active'),
('GR', 'GOODRIDE', 'Active'),
('GT', 'GOODTRIP', 'Active'),
('GULF', 'GULF', 'Active'),
('GY', 'GOODYEAR', 'Active'),
('H', 'HITACHI', 'Active'),
('HK', 'HKยางเล็ก', 'Active'),
('HK.', 'HK ยางใหญ่', 'Active'),
('HR', 'HIHERO', 'Active'),
('HT', 'HUT TYRES', 'Active'),
('IRC', 'IRC', 'Active'),
('KD', 'KENDA', 'Active'),
('KM', 'KUMHO', 'Active'),
('LE', 'LEAO', 'Active'),
('LL', 'LINGLONG ยางใหญ่', 'Active'),
('LLIT', 'LINGLONG ยางเล็ก', 'Active'),
('LS', 'LANDSAIL', 'Active'),
('MAX001', 'SEVEN FIFTH', 'Active'),
('MAX002', 'YACHIYODA', 'Active'),
('MAX003', 'LENSO', 'Active'),
('MAX004', 'THE ONE MAX', 'Active'),
('MAX005', 'LTC', 'Active'),
('MAX006', 'มาสเจสติค', 'Active'),
('MAX007', 'บวรพัฒน์', 'Active'),
('MAX008', 'วีลแกลเลอรี่', 'Active'),
('MAX009', 'KC WHEEL', 'Active'),
('MAX010', 'TK SMART', 'Active'),
('MAX011', 'สแตมฟอร์ด', 'Active'),
('MAX012', 'แอล จี ออโต้วีล', 'Active'),
('MAX013', 'อีโมชั่นฯ', 'Active'),
('MAX014', 'ออโต้เพอร์ฟอเม้นท์', 'Active'),
('MAX015', 'HOF', 'Active'),
('MK', 'MICKEY THOMPSON', 'Active'),
('ML', 'MLยางเล็ก', 'Active'),
('ML.', 'ML ยางใหญ่', 'Active'),
('MS', 'MARSHAL', 'Active'),
('MT', 'MASTER', 'Active'),
('MX', 'MAXXIS', 'Active'),
('MX.', 'MX', 'Active'),
('MXR', 'MAXIRICE', 'Active'),
('NK', 'NIKA', 'Active'),
('NT', 'NITTO', 'Active'),
('OT', 'OTANI', 'Active'),
('P', 'รวมสินค้ามือ 2', 'Active'),
('P01', 'อะไหล่นอก', 'Active'),
('PK-2013', 'ยางปีเก่ารวมยี่ห้อ <= 2013', 'Active'),
('PL', 'PIRELLI', 'Active'),
('PR', 'PRINX', 'Active'),
('SL', 'SAILUN', 'Active'),
('SP', 'SUPERSTONE', 'Active'),
('ST', 'สยามไทร์', 'Active'),
('SUMAX', 'SUMAX', 'Active'),
('TATA', 'TATA', 'Active'),
('TATA-P08', 'TATA-PEN', 'Active'),
('TATA-P09', 'TATA-เบาะ', 'Active'),
('TL', 'TIANLI', 'Active'),
('TY', 'TOYO ยางเล็ก', 'Active'),
('UR', 'URยางเล็ก', 'Active'),
('VALVOLINE', 'วาโวลีน จีอีโอ', 'Active'),
('VB', 'VEE RUBBER', 'Active'),
('WIL', 'กะทะล้อ', 'Active'),
('WTL', 'WESTLAKE', 'Active'),
('YK', 'YOKOHAMA', 'Active')
ON DUPLICATE KEY UPDATE brand_name = VALUES(brand_name), status = VALUES(status);
