<?php

$select_query_sale = "
SELECT 
DOC1.DI_KEY DI_KEY1,
DOC2.DI_KEY DI_KEY2,
FORMAT (DOC1.DI_DATE, 'dd/MM/yyyy ') as DI_DATE,
DOC1.DI_REF    BUY_REF,
DOC1.DI_DATE    BUY_DATE,
ARD_DUE_DA DUE_DATE,
ARD_B_AMT  BUY_AMOUNT,
DOC2.DI_REF    PAY_REF, 
DOC2.DI_DATE    PAY_DATE,
ARP_BAHT  PAY_BAHT ,
ARFILE.AR_CODE,
ARFILE.AR_NAME,
SALESMAN.SLMN_CODE,
SALESMAN.SLMN_NAME,
CHEQUEIN.CQIN_CHEQUE_NO,
BANKFILE.BANK_INITIAL,BANKFILE.BANK_T_NAME

FROM
DOCTYPE,
ARDETAIL,
ARPAYMENT,
DOCINFO DOC1,
DOCINFO DOC2,
ARFILE,  
SLDETAIL,
SALESMAN,
CHEQUEIN,
BANKFILE  ";

$sql_cond = "
WHERE
DOCINFO.DI_DT = DOCTYPE.DT_KEY AND
DOCTYPE.DT_PROPERTIES = 307 AND
ARP_ARD=ARD_KEY  AND
ARD_DI=DOC1.DI_KEY  AND
ARP_DI=DOC2.DI_KEY  AND
ARDETAIL.ARD_AR=ARFILE.AR_KEY   AND
( DOC1.DI_KEY = SLDETAIL.SLD_DI ) AND
(SLDETAIL.SLD_SLMN = SALESMAN.SLMN_KEY) AND 

CHEQUEIN.CQIN_DI = DOC2.DI_KEY AND 

BANKFILE.BANK_KEY = CHEQUEIN.CQIN_BANK AND 

-- DOC1.DI_REF like 'IV01256506/1511' 
-- DOC2.DI_REF = 'RR01256506/802' ";

$sql_order = "  
ORDER  BY
DOC1.DI_DATE ,
DOC1.DI_REF  
 ";