<?php

$select_query = "
SELECT
    S.SKU_KEY,
    S.SKU_CODE, 
    S.SKU_NAME,
    S.SKU_BRN,
    S.SKU_ICCAT,
    S.SKU_S_UTQ,
    S.SKU_K_UTQ,
    S.SKU_VAT_TY,
    S.SKU_VAT,
    S.SKU_COST_TY,
    S.SKU_STD_COST,
    S.SKU_STOCK,
    S.SKU_SKUALT,
    S.SKU_WH_TY,
    S.SKU_WH_RATE,
    S.SKU_MSG_1,
    S.SKU_MSG_2,
    S.SKU_MSG_3,
    B.BRN_NAME,
    C.ICCAT_NAME,
    ALT.SKUALT_NAME,
    G.GOODS_CODE,
    G.GOODS_ALIAS, 
    G.GOODS_WEIGHT,
    U.UTQ_NAME,
    A.ARPLU_U_PRC,
    A.ARPLU_U_DSC,
    T.TAG_NAME,
    TAB.ARPRB_CODE,
    TAB.ARPRB_NAME,
    T.TAG_CODE,
    G.GOODS_VOLUME,
    C.ICCAT_CODE,
    D.ICDEPT_CODE,
    B.BRN_CODE,
    TAB.ARPRB_VATIO,
    G.GOODS_PRICE
FROM SKUMASTER S WITH (NOLOCK)
INNER JOIN SKUALT ALT WITH (NOLOCK) ON S.SKU_SKUALT = ALT.SKUALT_KEY
INNER JOIN BRAND B WITH (NOLOCK) ON S.SKU_BRN = B.BRN_KEY
INNER JOIN ICCAT C WITH (NOLOCK) ON S.SKU_ICCAT = C.ICCAT_KEY
INNER JOIN ICDEPT D WITH (NOLOCK) ON S.SKU_ICDEPT = D.ICDEPT_KEY
INNER JOIN GOODSMASTER G WITH (NOLOCK) ON S.SKU_KEY = G.GOODS_SKU
INNER JOIN UOFQTY U WITH (NOLOCK) ON G.GOODS_UTQ = U.UTQ_KEY
INNER JOIN ARPLU A WITH (NOLOCK) ON G.GOODS_KEY = A.ARPLU_GOODS
INNER JOIN PRICETAG T WITH (NOLOCK) ON A.ARPLU_TAG = T.TAG_KEY
INNER JOIN ARPRICETAB TAB WITH (NOLOCK) ON A.ARPLU_ARPRB = TAB.ARPRB_KEY
";

$sql_cond = " WHERE (
    C.ICCAT_CODE LIKE '1SAC%' OR 
    C.ICCAT_CODE LIKE '2SAC%' OR 
    C.ICCAT_CODE LIKE '3SAC%' OR 
    C.ICCAT_CODE LIKE '4SAC%' OR 
    C.ICCAT_CODE LIKE '5SAC%' OR 
    C.ICCAT_CODE LIKE '6SAC%' OR 
    C.ICCAT_CODE LIKE '7SAC%' OR 
    C.ICCAT_CODE LIKE '8SAC%' OR 
    C.ICCAT_CODE LIKE '9SAC%'
) "; // คุณสามารถเพิ่มเงื่อนไขการกรองอื่นๆ ต่อจากตรงนี้ได้

$sql_order = " ORDER BY TAB.ARPRB_CODE";