<?php
$select_query_stock = " SELECT
 ICCAT.ICCAT_CODE,
 ICCAT.ICCAT_NAME,
 DOCINFO.DI_DATE,
 SKUMASTER.SKU_CODE,
 SKUMASTER.SKU_NAME,
 WAREHOUSE.WH_CODE,
 WAREHOUSE.WH_NAME,
 WARELOCATION.WL_CODE,
 WARELOCATION.WL_NAME,
 UOFQTY.UTQ_QTY,
 SUM(SKUMOVE.SKM_QTY) QTY
FROM
  SKUMASTER WITH (NOLOCK)
  JOIN ICCAT WITH (NOLOCK) ON SKUMASTER.SKU_ICCAT=ICCAT.ICCAT_KEY
  JOIN UOFQTY WITH (NOLOCK) ON SKUMASTER.SKU_S_UTQ=UOFQTY.UTQ_KEY 
  JOIN SKUMOVE WITH (NOLOCK) ON SKUMASTER.SKU_KEY = SKUMOVE.SKM_SKU
  JOIN WARELOCATION WITH (NOLOCK) ON SKUMOVE.SKM_WL=WARELOCATION.WL_KEY 
  JOIN WAREHOUSE WITH (NOLOCK) ON WARELOCATION.WL_WH=WAREHOUSE.WH_KEY
  JOIN DOCINFO WITH (NOLOCK) ON SKUMOVE.SKM_DI=DOCINFO.DI_KEY ";

$sql_cond_stock = " WHERE
 SKUMASTER.SKU_STOCK <> 0 ";

$sql_group_stock = " GROUP BY
 ICCAT.ICCAT_CODE,
 ICCAT.ICCAT_NAME,
 SKUMASTER.SKU_CODE,
 SKUMASTER.SKU_NAME,
 DOCINFO.DI_DATE,
 WAREHOUSE.WH_CODE,
 WAREHOUSE.WH_NAME,
 WARELOCATION.WL_CODE,
 WARELOCATION.WL_NAME,
 UOFQTY.UTQ_QTY ";

$sql_order_stock = " ORDER BY
  ICCAT.ICCAT_CODE,
  SKUMASTER.SKU_CODE,
  WAREHOUSE.WH_CODE,
  WARELOCATION.WL_CODE ASC ";



