<?php
// ปรับปรุงโดยใช้ INNER JOIN เพื่อให้ระบบ Skip ข้อมูลที่ไม่ครบเงื่อนไขโดยอัตโนมัติ
// และเพิ่ม AR_CODE เข้ามาใน Query หลักเลย เพื่อลดการวนลูป Query ใน PHP (Performance ดีขึ้น)

$str_sql_comm = " SELECT 
    TRANSTKD.TRD_KEY, 
    ADDRBOOK.ADDB_KEY, 
    ADDRBOOK.ADDB_BRANCH, 
    ADDRBOOK.ADDB_SEARCH,
    ADDRBOOK.ADDB_ADDB_1, 
    ADDRBOOK.ADDB_ADDB_2,
    ADDRBOOK.ADDB_ADDB_3,  
    ADDRBOOK.ADDB_COMPANY,
    ADDRBOOK.ADDB_PHONE,
    DOCINFO.DI_REF, 
    DOCINFO.DI_DATE,
    DAY(DOCINFO.DI_DATE) AS DI_DAY,
    MONTH(DOCINFO.DI_DATE) AS DI_MONTH,
    YEAR(DOCINFO.DI_DATE) AS DI_YEAR,
    SKUMASTER.SKU_CODE, 
    SKUMASTER.SKU_NAME, 
    TRANSTKD.TRD_QTY,
    TRANSTKD.TRD_Q_FREE,
    TRANSTKD.TRD_U_PRC,
    TRANSTKD.TRD_B_SELL,
    TRANSTKD.TRD_B_VAT,
    TRANSTKD.TRD_B_AMT
FROM TRANSTKH
INNER JOIN TRANSTKD ON TRANSTKH.TRH_KEY = TRANSTKD.TRD_TRH
INNER JOIN DOCINFO ON DOCINFO.DI_KEY = TRANSTKH.TRH_DI
INNER JOIN SKUMASTER ON TRANSTKD.TRD_SKU = SKUMASTER.SKU_KEY
INNER JOIN ADDRBOOK ON TRANSTKH.TRH_SHIP_ADDB = ADDRBOOK.ADDB_KEY
INNER JOIN ARADDRESS ON ADDRBOOK.ADDB_KEY = ARADDRESS.ARA_ADDB  -- จุดที่ใช้ Skip รายการที่ไม่มีที่อยู่
INNER JOIN ARDETAIL ON ARDETAIL.ARD_AR = ARADDRESS.ARA_AR AND DOCINFO.DI_KEY = ARDETAIL.ARD_DI
WHERE 1=1 ";

// หมายเหตุ: ใส่ WHERE 1=1 ไว้เพื่อให้ตัวแปร $sql_and ที่ต่อท้ายทำงานได้ทันทีโดยไม่ต้องเช็คว่าเป็นเงื่อนไขแรกหรือไม่

$str_sql_order = " ORDER BY ADDB_COMPANY, TRD_KEY DESC, SKU_CODE ";